name: lotto
description: sweetSD's lotto app project.
publish_to: 'none'
version: 1.1.3+20

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  qrscan: ^0.3.2
  intl: ^0.18.1
  http: ^0.13.3
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.0.9
  image_picker: ^0.8.2
  fluttertoast: ^8.0.8  
  json_annotation: ^4.0.1
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  permission_handler: ^10.2.0
  percent_indicator: ^4.2.3
  firebase_core: ^2.10.0
  firebase_database: ^10.1.1
  device_info: ^2.0.2
  google_maps_flutter: ^2.0.6
  flutter_google_places: ^0.3.0
  geolocator: ^9.0.2
  html: ^0.15.0
  flutter_local_notifications: ^14.0.0+1
  google_mobile_ads: ^3.0.0
  firebase_messaging: ^14.4.1
  firebase_messaging_web: ^3.3.1
  firebase_core_web: ^2.3.0
  loading_indicator: ^3.0.1
  webview_flutter: ^4.2.0
  cp949_dart: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.6
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Binggrae
      fonts:
        - asset: assets/fonts/Binggrae-Bold.ttf
    - family: NexonLv2
      fonts:
        - asset: assets/fonts/NEXON Lv2 Gothic.ttf